# Generated by Django 5.2.4 on 2025-07-22 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_shippingclass_tag_category_product_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_products', models.PositiveIntegerField(default=0)),
                ('can_use_variants', models.BooleanField(default=False)),
                ('can_create_discounts', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart.package'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=60, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='smart.product')),
            ],
            options={
                'ordering': ['sku'],
                'unique_together': {('product', 'sku')},
            },
        ),
        migrations.RenameModel(
            old_name='VariationOption',
            new_name='ProductVariationOption',
        ),
        migrations.RenameModel(
            old_name='VariationType',
            new_name='ProductVariationType',
        ),
        migrations.CreateModel(
            name='VariantOptionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.productvariationoption')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='smart.productvariant')),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.productvariationtype')),
            ],
            options={
                'unique_together': {('variant', 'variation_type')},
            },
        ),
    ]
