# Generated by Django 5.2.4 on 2025-07-22 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_package_alter_product_slug_user_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='labels/icons/')),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sliders/images/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sliders/backgrounds/')),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('paragraph_color', models.CharField(blank=True, help_text='Hex color (e.g. #000000)', max_length=7, null=True)),
                ('heading_h3', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_h3_color', models.CharField(blank=True, help_text='Hex color (e.g. #ff0000)', max_length=7, null=True)),
                ('heading_h5', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_h5_color', models.CharField(blank=True, help_text='Hex color (e.g. #333333)', max_length=7, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.RenameModel(
            old_name='Discount',
            new_name='ProductDiscount',
        ),
        migrations.CreateModel(
            name='ProductLabelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_comment', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.productlabel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_requests', to='smart.product')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'label')},
            },
        ),
    ]
