# Generated by Django 5.2.4 on 2025-07-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_productlabel_slider_rename_discount_productdiscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='background_image',
            field=models.ImageField(default=1, upload_to='sliders/backgrounds/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders/images/'),
        ),
    ]
