# Generated by Django 5.1.5 on 2025-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_locations/')),
            ],
        ),
    ]
