# Generated by Django 5.2.4 on 2025-07-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_alter_slider_background_image_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text_alignment',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Right')], default=0),
        ),
    ]
