# Generated by Django 5.2.4 on 2025-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0007_slider_text_alignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutusPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g., contact-us, become-a-vendor', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='media/AboutUs-page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogListPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g., contact-us, become-a-vendor', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='media/Blog-List-page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g., contact-us, become-a-vendor', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='media/Blog-page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/contact_locations/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g., contact-us, become-a-vendor', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='media/contact_page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaqsPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g., contact-us, become-a-vendor', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='media/Faq-page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendorregisterPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g., contact-us, become-a-vendor', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='media/vendor_register_page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g., contact-us, become-a-vendor', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='media/Wishlist-page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
