# Generated by Django 5.2.4 on 2025-07-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0008_aboutuspageheader_bloglistpageheader_blogpageheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Free'), (1, 'Paid')], default=0),
        ),
    ]
