# Generated by Django 5.2.4 on 2025-07-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0010_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcompanyoverview',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/tax_certificates/'),
        ),
        migrations.AddField(
            model_name='vendorcompanyoverview',
            name='trade_licence',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/trade_licences/'),
        ),
    ]
