# Generated by Django 5.2.4 on 2025-07-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0011_vendorcompanyoverview_tax_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorverification',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Rejected')], default='0', help_text='Current verification status of the vendor.', max_length=1),
        ),
    ]
