# Generated by Django 5.2.4 on 2025-07-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0012_vendorverification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug_name',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smart.categorytype'),
            preserve_default=False,
        ),
    ]
