# Generated by Django 5.1.5 on 2025-07-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0013_faqspageheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistPageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text='e.g., contact-us, become-a-vendor', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='media/Wishlist-page_headers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
