# Generated by Django 5.2.4 on 2025-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0013_categorytype_rename_slug_name_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/brands/')),
            ],
        ),
    ]
