# Generated by Django 5.1.5 on 2025-08-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0016_alter_categorybanner_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybanner',
            name='button_link',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
