# Generated by Django 5.1.5 on 2025-08-03 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0018_advertisingbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingbanner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertising_banners', to='smart.category'),
        ),
    ]
