# Generated by Django 5.1.5 on 2025-08-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0019_advertisingbanner_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisingbanner',
            name='category',
        ),
        migrations.AddField(
            model_name='advertisingbanner',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='advertising_banners', to='smart.category'),
        ),
    ]
