# Generated by Django 5.2.4 on 2025-08-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0023_district_address_order_orderpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Very Poor'), (2, 'Not That Bad'), (3, 'Average'), (4, 'Good'), (5, 'Perfect')])),
                ('text', models.TextField(verbose_name='Review Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='smart.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
