# Generated by Django 5.2.4 on 2025-08-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0026_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart.district'),
        ),
        migrations.AlterField(
            model_name='address',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart.thana'),
        ),
    ]
