# Generated by Django 5.1.5 on 2025-08-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0027_alter_address_district_alter_address_thana'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
