# Generated by Django 5.1.5 on 2025-08-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0028_product_model_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
