# Generated by Django 5.2.4 on 2025-08-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0029_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorverification',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0, help_text='Current verification status of the vendor.'),
        ),
    ]
