# Generated by Django 5.1.5 on 2025-08-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0030_address_created_at_address_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, help_text='True if product is newly uploaded or updated'),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (required if rejected)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/small/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Pending'), (3, 'Rejected'), (4, 'Approved')], default=2),
        ),
    ]
