# Generated by Django 5.2.4 on 2025-08-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0031_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbnails/small/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/small/'),
        ),
    ]
