# Generated by Django 5.2.4 on 2025-08-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0032_product_thumbnail_small_productimage_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
