# Generated by Django 5.1.5 on 2025-08-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0032_ordernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
