# Generated by Django 5.2.4 on 2025-08-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0033_alter_product_publish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, help_text='True if product is newly uploaded or updated'),
        ),
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (required if rejected)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Pending'), (3, 'Rejected'), (4, 'Approved')], default=2),
        ),
    ]
