# Generated by Django 5.1.5 on 2025-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0036_vendorordernotification_vendorordernotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='categories/banners/'),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail_small',
            field=models.ImageField(blank=True, null=True, upload_to='categories/thumbnails/'),
        ),
    ]
