# Generated by Django 5.1.5 on 2025-08-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0037_category_banner_category_thumbnail_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
