# Generated by Django 5.2.4 on 2025-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0037_remove_category_image_category_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
