# Generated by Django 5.1.5 on 2025-08-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0039_deliverytype_deliverycharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='thana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
