# Generated by Django 5.1.5 on 2025-08-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0043_alter_order_discount_total_alter_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart.district'),
        ),
        migrations.AlterField(
            model_name='address',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart.thana'),
        ),
    ]
