# Generated by Django 5.2.4 on 2025-08-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0046_alter_address_district_alter_address_thana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='thana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
