# Generated by Django 5.2.4 on 2025-09-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0047_alter_address_district_alter_address_thana'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
