# Generated by Django 5.2.4 on 2025-09-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0050_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for product demonstration', max_length=500, null=True),
        ),
    ]
