# Generated by Django 5.1.5 on 2025-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0051_product_youtube_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtube_video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube video URL for product demonstration', max_length=500, null=True),
        ),
    ]
