# Generated by Django 5.1.5 on 2025-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0052_alter_product_youtube_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
