# Generated by Django 5.2.4 on 2025-10-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0052_order_free_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_free_product',
            field=models.BooleanField(default=False),
        ),
    ]
