# Generated by Django 5.1.5 on 2025-09-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0053_order_free_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_free_product',
            field=models.BooleanField(default=False),
        ),
    ]
