# Generated by Django 5.2.4 on 2025-10-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0053_orderitem_is_free_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='productdiscount',
            name='min_price',
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='min_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
