# Generated by Django 5.2.4 on 2025-10-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0054_remove_productdiscount_max_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Logo', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
