# Generated by Django 5.2.4 on 2025-10-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0055_sitelogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('replied', 'Replied')], default='new', max_length=10),
        ),
    ]
