# Generated by Django 5.2.4 on 2025-10-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0056_contactmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-x-twitter', 'Twitter'), ('fab fa-instagram', 'Instagram'), ('fab fa-linkedin-in', 'LinkedIn'), ('fab fa-youtube', 'YouTube'), ('fab fa-whatsapp', 'WhatsApp'), ('fab fa-tiktok', 'TikTok'), ('fab fa-pinterest', 'Pinterest'), ('fab fa-snapchat-ghost', 'Snapchat'), ('fab fa-telegram-plane', 'Telegram'), ('fab fa-reddit-alien', 'Reddit'), ('fab fa-github', 'GitHub'), ('fab fa-dribbble', 'Dribbble'), ('fab fa-behance', 'Behance'), ('fab fa-discord', 'Discord'), ('fab fa-medium-m', 'Medium'), ('fab fa-stack-overflow', 'Stack Overflow'), ('fab fa-vimeo-v', 'Vimeo'), ('fab fa-slack', 'Slack'), ('fab fa-flickr', 'Flickr'), ('fab fa-tumblr', 'Tumblr'), ('fab fa-yelp', 'Yelp'), ('fab fa-soundcloud', 'SoundCloud'), ('fab fa-dev', 'Dev.to'), ('fab fa-codepen', 'CodePen')], default='fab fa-facebook-f', help_text='Select the icon for the social platform', max_length=50)),
                ('link', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Social Icon',
                'verbose_name_plural': 'Social Icons',
            },
        ),
    ]
