# Generated by Django 5.1.5 on 2025-10-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0058_address_first_name_address_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Smart DSM', max_length=200)),
                ('site_description', models.TextField(default='Your trusted marketplace')),
                ('site_keywords', models.TextField(default='marketplace, ecommerce')),
                ('og_image', models.ImageField(blank=True, help_text='Recommended size: 1200x630px', null=True, upload_to='meta/')),
                ('favicon', models.ImageField(blank=True, help_text='Recommended size: 512x512px', null=True, upload_to='meta/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
